# Generated by Django 4.2 on 2023-11-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_relatos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=300)),
                ('data_nascimento', models.DateField()),
                ('caracteristicas', models.TextField(max_length=1000)),
                ('historia', models.TextField(max_length=5000)),
                ('sobre_mim', models.TextField(max_length=5000)),
            ],
        ),
    ]
