# Generated by Django 4.2 on 2023-11-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_calendario_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='data',
            field=models.DateField(),
        ),
    ]
