# Generated by Django 4.2 on 2023-11-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_calendario_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('Feliz', 'Feliz'), ('Normal', 'Normal'), ('Triste', 'Triste')], max_length=15)),
            ],
        ),
    ]
