# Generated by Django 4.2 on 2023-11-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Feliz', 'F'), ('Normal', 'N'), ('Triste', 'T')], max_length=15),
        ),
    ]
