# Generated by Django 4.2 on 2023-11-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_alter_status_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=1500)),
                ('feedback', models.CharField(choices=[('Feliz', 'F'), ('Normal', 'N'), ('Triste', 'T')], max_length=15)),
            ],
        ),
    ]
