# Generated by Django 4.2 on 2023-11-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatos',
            name='status',
            field=models.CharField(choices=[('Feliz', 'Feliz'), ('Normal', 'Normal'), ('Triste', 'Triste')], default='Feliz', max_length=10),
        ),
    ]
